### ISSUE TITLE
storage tables need to be versioned

### ISSUE THREAD

**Issue by 65278** [onemoredata/bagger#6]
We need to know at which point in time which indexes and dimensions are available (e.g. checking availability of indexes for queries).
Therefore we require a table which roughly has the following scheme:

```
config_id int primary key;
date timestamp_tz;
```
storage.dimensions and storage.indexes need to refer to `config_id` as foreign keys.
Inserting/Removing indices/dimensions must create a new config_id and copy all already existing indices/dimensions.

More elegant solutions welcome.

**Comment by 65278** [comment]
Brain activity happened: it's enough if we store indexes/dimensions with a start timestamp and on remove operations, we add a finish timestamp.
These entries can be garbage collected when retention is reached.

**Comment by einhverfr** [comment]
I have some larger thoughts here and will start on this one this week.  In particular I think this would benefit from an interval type as well, though probably not on the storage side.  I.e. being able to effectively use gist indexes and range queries for overlap would be helpful.

**Comment by einhverfr** [comment]
Once I have this fully fixed for dimensions, I will tackle this for indexes.  #43 is a prerequisite to doing this for dimensions and indexes.
