### ISSUE TITLE
storage.dimensions: fieldname may not be at json root level

### ISSUE THREAD

**Issue by 65278** [onemoredata/bagger#7]
storage.dimensions requires a fieldname:
https://github.com/onemoredata/bagger/blob/4f1cf20b6d8ad571f49bd86311a1de3640545970/sql/lenkwerk/storage/storage.sql#L52
Presumably this field is then used in table generation.

Now consider that the field may not be at the root level of a json document:
```
{
    "timestamp": ...,
    "data": {
        "servicename": "service"
    }
}
```

I propose that we require a jsonpointer field which allows us to decouple fieldname and position in json.

Edit:  Proposed path foward:

- [x] Add something approximating JSON pointers with appropriate conversions in the database too.  I plan to use text[] for that.
- [x] Add min/max timestamps for dimensions
- [x] Add database tests for the whole bit.

**Comment by 65278** [comment]
More brain activity: how would the insert trigger know about this?
This is solvable by having a copy of fields available on each bagger storage node, but that's also an unsolved problem.

**Comment by einhverfr** [comment]
So my thinking is indeed to have some sort of logical replication to the bagger nodes.  The problem is scaling and ensuring that replication.  The question of whether we use etcd as effectively a replication multiplexer and notification service for such things is relevant here.

On the whole this has to be done for 1.0, but I will probably start on it maybe next week if I am able.

**Comment by einhverfr** [comment]
Also regarding json pointers, my thinking is to have a text[] array and some logic to change it to json pointers.  We could eventually write a custom type to do the json pointers though.

**Comment by einhverfr** [comment]
BTW for the insert trigger, I think we can assume that all tables needed exist in every bagger storage node.  We just need to build the infra to do this.

**Comment by 65278** [comment]
We could go about it in a most primitive manner: pg_dump to a kafka topic, bagger nodes restore from kafka topic. Not even a logical subscription required.
For now I'll just assume the required data is there.

**Comment by einhverfr** [comment]
I will try to solve the Lenkwerk side on this today or tomorrow.

As I see it, this means:
1.  dimensions need to have something approximating a JSON pointer (I will use a text array)
2. dimensions need to have time bounds.  I think for the initial estimate, I will truncate these to the level of an hour.

**Comment by einhverfr** [comment]
(I will also add full db tests for the dimensions pm in the process)

**Comment by einhverfr** [comment]
Ok so rethinking this a little.  I see three possible approaches:
1.  text arrays, perhaps available via other data types too.
2.  jsonpath object with wildcards banned.
3.  json pointers.

Of course all three can be converted to eachother so maybe I will try to have all three options shortly.
